export const TasksActionTypes = {
	SET_ALL_TASKS: 'SET_ALL_TASKS',
	TASK_CREATED: 'TASK_CREATED',
	FETCHING_TASKS: 'FETCHING_TASKS',
	FETCHING_SUCCESS: 'FETCHING_SUCCESS',
	IS_LOADING: 'IS_LOADING',
	IS_DONE_LOADING: 'IS_DONE_LOADING',
	CREATE_TASK_COMMENT: 'CREATE_TASK_COMMENT',
};
