export const ProjectActionTypes = {
	GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
	PROJECT_CREATED: 'PROJECT_CREATED',
	SET_ONE_PROJECT: 'SET_ONE_PROJECT',
	PROJECT_LOADING: 'PROJECT_LOADING',
	PROJECT_LOADED: 'PROJECT_LOADED',
};
